#!/usr/bin/env zsh
set -euo pipefail

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="${0:A:h}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  -c "${BASEDIR}/${CONFIG}" "${@}"
