" Default settings
set nocompatible
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
set autoindent
set ruler
set number
set showcmd
set showmatch
set ignorecase
set smartcase
set incsearch
set hlsearch
set mouse=a
set lazyredraw
set noshowmode
set noerrorbells
set novisualbell
set nobackup
set termguicolors

syntax on
set background=dark

" Make <Leader> more accessible
let mapleader = ","

" Window keybinds
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" jk to escape
inoremap jk <Esc>

" vim-plug
call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'

Plug 'airblade/vim-gitgutter'
Plug 'easymotion/vim-easymotion'
Plug 'fmoralesc/vim-tutor-mode'
Plug 'godlygeek/tabular'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'kristijanhusak/vim-hybrid-material'
Plug 'scrooloose/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'valloric/youcompleteme'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

" Theme
colorscheme hybrid_material
let g:airline_theme = "tomorrow"

" EasyMotion
map <Leader> <Plug>(easymotion-prefix)

"" JK motions: Line motions
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
