" Default settings
set nocompatible
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
set autoindent
set ruler
set number
set showcmd
set showmatch
set showmode
set ignorecase
set smartcase
set incsearch
set hlsearch
set mouse=a
set lazyredraw
set noerrorbells
set novisualbell
set nobackup
set termguicolors

syntax on
set background=dark

" Make <Leader> more accessible
let mapleader = ","

" Window keybinds
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" jk to escape
inoremap jk <Esc>

" vim-plug
call plug#begin('~/.vim/plugged')

Plug 'airblade/vim-gitgutter'
Plug 'easymotion/vim-easymotion'
Plug 'flazz/vim-colorschemes'
Plug 'fmoralesc/vim-tutor-mode'
Plug 'godlygeek/tabular'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'valloric/youcompleteme'
Plug 'vim-airline/vim-airline'

call plug#end()

" EasyMotion
map <Leader> <Plug>(easymotion-prefix)

"" JK motions: Line motions
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)

" Theme
let $NVIM_TUI_ENABLE_TRUE_COLOR = 1
colorscheme material
