tap "homebrew/cask"

tap "homebrew/services"

tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

tap "railwaycat/emacsmacport"

cask_args appdir: "/Applications"

## Brews
# macOS App Store
brew "mas"

# Shell essentials
brew "zsh"
brew "antibody"
brew "tmux"

# Replacements for system programs
brew "bash"
brew "coreutils"
brew "grep"
brew "vim"

# Version control
brew "git"
brew "mercurial"
brew "subversion" # Needed for font-source-code-pro

# Git helpers
brew "git-delta"
brew "git-filter-repo"
brew "git-lfs"

# Editors
brew "neovim"

# Languages and package managers
brew "java"
brew "node"
brew "python"
brew "solidity"

brew "corepack"    # Manages node
brew "opam"        # Manages ocaml
brew "rbenv"       # Manages ruby
brew "rustup-init" # Manages rust

# Shell niceties
brew "fzf"
brew "htop"
brew "jq"
brew "shellcheck"
brew "tldr"
brew "tree"
brew "wget"

# Rust-based shell tools
brew "bat"       # cat
brew "exa"       # ls
brew "hyperfine" # bench
brew "fd"        # find
brew "ripgrep"   # grep
brew "xsv"

# Miscellaneous tools
brew "dive"
brew "ffmpeg"
brew "fswatch"
brew "gnupg"
brew "k3d"
brew "magic-wormhole"
brew "pandoc"
brew "pngcrush"
brew "pngquant"

## Casks
# Fonts
cask "font-dejavu"
cask "font-fira-sans"
cask "font-source-code-pro"

# Programming tools
cask "docker"
cask "emacs-mac"
cask "google-cloud-sdk"
cask "iterm2"

# Utilities
cask "alfred"
cask "appcleaner"
cask "audio-hijack"
cask "bartender"
cask "karabiner-elements"
cask "loopback"
cask "rectangle"
cask "scroll-reverser"
cask "steelseries-exactmouse-tool"

# Browsers
cask "firefox-beta"
cask "google-chrome-beta"

# Applications
cask "adobe-acrobat-reader"
cask "dropbox"
cask "iina"
cask "notion"
cask "private-internet-access"
cask "spotify"
cask "steam"
cask "transmission"
cask "twobird"
cask "visual-studio-code"

# Communication
cask "discord"
cask "zoom"

## macOS applications
mas "Xcode", id: 497799835

mas "1Password 7", id: 1333542190
mas "Affinity Photo", id: 824183456
mas "DaisyDisk", id: 411643860
mas "Deliveries", id: 290986013
mas "Fantastical", id: 975937182
mas "Messenger", id: 1480068668
mas "Slack for Desktop", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Things 3", id: 904280696
