tap "homebrew/cask"

tap "homebrew/services"

tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

tap "beeftornado/rmtree"
tap "d12frosted/emacs-plus"
tap "ethereum/ethereum"
tap "getantibody/tap"

cask_args appdir: "/Applications"

## Brews
# macOS App Store
brew "mas"

# Shell essentials
brew "zsh"
brew "antibody"
brew "tmux"

# Replacements for system programs
brew "bash"
brew "coreutils"
brew "grep"
brew "vim"

# Git and helpers
brew "git"

brew "diff-so-fancy"
brew "git-lfs"

# Editors
brew "emacs-plus"
brew "neovim"

# Languages and package managers
brew "java"
brew "node"
brew "python"
brew "solidity"

brew "opam"        # Manages ocaml
brew "rbenv"       # Manages ruby
brew "rustup-init" # Manages rust

# Shell niceties
brew "fzf"
brew "htop"
brew "jq"
brew "shellcheck"
brew "tldr"
brew "tree"
brew "wget"

# Rust-based shell tools
brew "bat"       # cat
brew "exa"       # ls
brew "hyperfine" # bench
brew "fd"        # find
brew "ripgrep"   # grep
brew "xsv"

# Miscellaneous tools
brew "dive"
brew "editorconfig"
brew "ffmpeg", args: [
    "with-fdk-aac", "with-freetype", "with-libass", "with-libvorbis",
    "with-libvpx", "with-opus", "with-sdl2", "with-x265"
]
brew "ffsend"
brew "fswatch"
brew "gnupg"
brew "k3d"
brew "pandoc"
brew "pngquant"
brew "svn" # Needed for font-source-code-pro

## Casks
# Essentials
cask "xquartz"

# Fonts
cask "font-fira-sans"
cask "font-hack"
cask "font-inconsolata"
cask "font-montserrat"
cask "font-open-sans"
cask "font-source-code-pro"

# Programming tools
cask "docker"
cask "iterm2"

# Utilities
cask "alfred"
cask "appcleaner"
cask "audio-hijack"
cask "bartender"
cask "karabiner-elements"
cask "loopback"
cask "scroll-reverser"
cask "spectacle"
cask "steelseries-exactmouse-tool"

# Browsers
cask "firefox-beta"
cask "google-chrome-beta"

# Applications
cask "adobe-acrobat-reader"
cask "anki"
cask "dropbox"
cask "iina"
cask "notion"
cask "private-internet-access"
cask "spotify"
cask "transmission"
cask "twobird"
cask "visual-studio-code"

# Communication
cask "discord"
cask "messenger"
cask "zoom"

## macOS applications
mas "Xcode", id: 497799835

mas "1Password 7", id: 1333542190
mas "Affinity Photo", id: 824183456
mas "DaisyDisk", id: 411643860
mas "Deliveries", id: 924726344
mas "Fantastical 2", id: 975937182
mas "The Unarchiver", id: 425424353
mas "Things 3", id: 904280696
