#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## Interactive shell variables
# Delay of zsh key sequences (like Esc), in 10 ms units
KEYTIMEOUT=1

# (GNU) ls formatting options
export BLOCK_SIZE="'1"       # Thousands separator for sizes
export TIME_STYLE="long-iso" # ISO 8601 datetimes

# Other aliases
alias ga="git add"
alias gfu="git fetch upstream"
alias gfmu="git pull upstream master"

update_python() {
  if (( $+commands[pip2] )); then
    pip2 install --upgrade pip
    pip2 freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip2 install -U
  fi

  if (( $+commands[pip3] )); then
    pip3 install --upgrade pip
    pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U
  fi
}

update_vim() {
  vim +PlugUpdate +qall
}

update_ycm() {
  pushd "$HOME/.vim/plugged/youcompleteme"
  ./install.py --clang-completer --js-completer --rust-completer
  popd
}

reload_tmux() {
  tmux source-file "$HOME/.tmux.conf"
}

## Custom programs
# PostgreSQL
alias pg_start="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias pg_stop="pg_ctl -D /usr/local/var/postgres stop -s -m fast"

# fzf
if [[ -d "/usr/local/opt/fzf" ]]; then
  # Auto-completion
  [[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.zsh" 2> /dev/null

  # Key bindings
  source "/usr/local/opt/fzf/shell/key-bindings.zsh"
fi
